import { v4 } from "uuid";

const BreakfastMealData = [
  {
    id: v4(),
    title: "Avocado",
    path: "Images/Breakfast/morning_avocado.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Banana",
    path: "Images/Breakfast/morning_banana.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Blueberries",
    path: "Images/Breakfast/morning_blueberries.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Coffee",
    path: "Images/Breakfast/morning_coffee.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Grapes",
    path: "Images/Breakfast/morning_grapes.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Kiwi",
    path: "Images/Breakfast/morning_kiwi.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Orange",
    path: "Images/Breakfast/morning_orange.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Papaya",
    path: "Images/Breakfast/morning_papaya.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Pineapple",
    path: "Images/Breakfast/morning_pineapple.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Raspberries",
    path: "Images/Breakfast/morning_raspberries.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Strawberry",
    path: "Images/Breakfast/morning_strawberry.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
  {
    id: v4(),
    title: "Watermelon",
    path: "Images/Breakfast/morning_watermelon.jpg",
    Qty: 0,
    sum: 0,
    cal: 100,
  },
];

export default BreakfastMealData;
