import { v4 } from "uuid";

const LunchMealData = [
  {
    id: v4(),
    title: "Broccoli",
    path: "Images/Lunch/noon_broccoli.jpg",
    Qty: 0,
    sum: 0,
    cal: 35,
  },
  {
    id: v4(),
    title: "Cabbage",
    path: "Images/Lunch/noon_cabbage.jpg",
    Qty: 0,
    sum: 0,
    cal: 25,
  },
  {
    id: v4(),
    title: "Capsicum",
    path: "Images/Lunch/noon_capcicum.jpg",
    Qty: 0,
    sum: 0,
    cal: 26,
  },
  {
    id: v4(),
    title: "Cauliflower",
    path: "Images/Lunch/noon_cauliflower.jpg",
    Qty: 0,
    sum: 0,
    cal: 25,
  },
  {
    id: v4(),
    title: "Corn",
    path: "Images/Lunch/noon_corn.jpg",
    Qty: 0,
    sum: 0,
    cal: 86,
  },
  {
    id: v4(),
    title: "Boiled Eggs",
    path: "Images/Lunch/noon_eggs.jpg",
    Qty: 0,
    sum: 0,
    cal: 155,
  },
  {
    id: v4(),
    title: "Pasta",
    path: "Images/Lunch/noon_pasta.jpg",
    Qty: 0,
    sum: 0,
    cal: 131,
  },
  {
    id: v4(),
    title: "Peas",
    path: "Images/Lunch/noon_peas.jpg",
    Qty: 0,
    sum: 0,
    cal: 81,
  },
  {
    id: v4(),
    title: "Pizza",
    path: "Images/Lunch/noon_pizza.jpg",
    Qty: 0,
    sum: 0,
    cal: 266,
  },
  {
    id: v4(),
    title: "Potato",
    path: "Images/Lunch/noon_potato.jpg",
    Qty: 0,
    sum: 0,
    cal: 77,
  },
  {
    id: v4(),
    title: "Pumpkin",
    path: "Images/Lunch/noon_pumpkin.jpg",
    Qty: 0,
    sum: 0,
    cal: 26,
  },
  {
    id: v4(),
    title: "Radish",
    path: "Images/Lunch/noon_radish.jpg",
    Qty: 0,
    sum: 0,
    cal: 16,
  },
];

export default LunchMealData;
