import { v4 } from "uuid";
const MealData = [
  {
    id: v4(),
    title: "Beef",
    path: "Images/Beef.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Bolied Eggs",
    path: "Images/Boiled Eggs.jpg",
    Qty: 0,
    cal:80,
    sum:0,
  },
  {
    id: v4(),
    title: "Bread",
    path: "Images/Bread.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Brocoli",
    path: "Images/Brocoli.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Chapati",
    path: "Images/Chapati.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Idli",
    path: "Images/Idli.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "CornFlakes",
    path: "Images/Corn.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Fried Rices",
    path: "Images/Fried Rice.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
  {
    id: v4(),
    title: "Noodles",
    path: "Images/noodles.jpg",
    Qty: 0,
    cal:100,
    sum:0,
  },
];
export default MealData;
